version: "3"

services:

  elasticsearch:
    image: elasticsearch:7.17.20
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node

  kibana:
    image: kibana:7.17.20
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200

  fscrawler:
    image: dadoonet/fscrawler:2.10-SNAPSHOT-ocr-es7
    volumes:
      # config
      - ./fscrawler:/root/.fscrawler
      # data
      - /mnt/e/datasets/datassette.org/Datassette/:/root/data/datassete
    command:
      - fscrawler
      - datassete